"""Models for the coding app."""

import hashlib

from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class CodingChallenge(models.Model):
    """
    Represents a coding challenge that users can attempt.

    Challenges can be generated by Claude or manually created.
    Two types: implement from scratch or modify existing code.
    """

    class ChallengeType(models.TextChoices):
        IMPLEMENT = "implement", _("Implement from Scratch")
        MODIFY = "modify", _("Modify Existing Code")

    class Difficulty(models.TextChoices):
        BEGINNER = "beginner", _("Beginner")
        INTERMEDIATE = "intermediate", _("Intermediate")
        ADVANCED = "advanced", _("Advanced")

    class Language(models.TextChoices):
        PYTHON = "python", _("Python")
        JAVASCRIPT = "javascript", _("JavaScript")
        SQL = "sql", _("SQL")
        GIT = "git", _("Git Commands")
        SHELL = "shell", _("Shell/Bash")
        DOCKER = "docker", _("Docker")

    class Source(models.TextChoices):
        CLAUDE_API = "claude_api", _("Claude API Generated")
        MANUAL = "manual", _("Manually Created")

    # Relationship
    subject = models.ForeignKey(
        "subjects.Subject",
        on_delete=models.CASCADE,
        related_name="coding_challenges",
        help_text=_("The subject area this challenge belongs to"),
    )

    # Challenge definition
    title = models.CharField(
        max_length=200,
        help_text=_("Brief title for the challenge"),
    )
    description = models.TextField(
        help_text=_("Full problem description with requirements"),
    )
    challenge_type = models.CharField(
        max_length=20,
        choices=ChallengeType.choices,
        default=ChallengeType.IMPLEMENT,
        db_index=True,
        help_text=_("Type of challenge: implement or modify"),
    )
    language = models.CharField(
        max_length=20,
        choices=Language.choices,
        default=Language.PYTHON,
        db_index=True,
        help_text=_("Programming language for this challenge"),
    )

    # Starter code (for modify challenges) or template (for implement)
    starter_code = models.TextField(
        blank=True,
        help_text=_("Initial code provided to the user"),
    )

    # Solution and evaluation criteria
    reference_solution = models.TextField(
        blank=True,
        help_text=_("Reference solution for evaluation context"),
    )
    evaluation_criteria = models.JSONField(
        default=list,
        help_text=_("List of criteria Claude should evaluate against"),
    )
    expected_output = models.TextField(
        blank=True,
        help_text=_("Expected output or behavior description"),
    )

    # Hints (optional, can be revealed progressively)
    hints = models.JSONField(
        default=list,
        help_text=_("List of hints that can be revealed"),
    )

    # Metadata
    difficulty = models.CharField(
        max_length=20,
        choices=Difficulty.choices,
        default=Difficulty.INTERMEDIATE,
        db_index=True,
        help_text=_("Difficulty level of the challenge"),
    )
    tags = models.JSONField(
        default=list,
        blank=True,
        help_text=_("Tags for categorizing the challenge"),
    )
    estimated_time_minutes = models.PositiveIntegerField(
        default=15,
        help_text=_("Estimated time to complete in minutes"),
    )

    # Source tracking
    source = models.CharField(
        max_length=20,
        choices=Source.choices,
        default=Source.CLAUDE_API,
        db_index=True,
        help_text=_("Where this challenge originated from"),
    )
    source_hash = models.CharField(
        max_length=64,
        blank=True,
        db_index=True,
        help_text=_("Hash for deduplication"),
    )

    # Status
    is_active = models.BooleanField(
        default=True,
        db_index=True,
        help_text=_("Whether this challenge is available for use"),
    )

    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]
        verbose_name = _("Coding Challenge")
        verbose_name_plural = _("Coding Challenges")
        indexes = [
            models.Index(fields=["subject", "difficulty", "is_active"]),
            models.Index(fields=["subject", "challenge_type", "is_active"]),
            models.Index(fields=["subject", "language", "is_active"]),
        ]

    def __str__(self) -> str:
        return f"{self.subject.name}: {self.title}"

    def save(self, *args, **kwargs) -> None:
        """Generate source hash if not provided."""
        if not self.source_hash and self.title and self.description:
            content = f"{self.subject_id}:{self.title}:{self.description[:500]}"
            self.source_hash = hashlib.sha256(content.encode()).hexdigest()
        super().save(*args, **kwargs)


class CodingSession(models.Model):
    """
    Represents a single coding challenge attempt by a user.

    Tracks the configuration, progress, and final evaluation.
    """

    class Status(models.TextChoices):
        IN_PROGRESS = "in_progress", _("In Progress")
        SUBMITTED = "submitted", _("Submitted for Evaluation")
        COMPLETED = "completed", _("Completed")
        ABANDONED = "abandoned", _("Abandoned")

    # Relationships
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="coding_sessions",
        help_text=_("The user attempting this challenge"),
    )
    subject = models.ForeignKey(
        "subjects.Subject",
        on_delete=models.CASCADE,
        related_name="coding_sessions",
        help_text=_("The subject area for this session"),
    )
    challenge = models.ForeignKey(
        CodingChallenge,
        on_delete=models.CASCADE,
        related_name="sessions",
        help_text=_("The challenge being attempted"),
    )

    # Configuration (snapshot from challenge at session start)
    challenge_type = models.CharField(
        max_length=20,
        choices=CodingChallenge.ChallengeType.choices,
        help_text=_("Type of challenge at time of session"),
    )
    difficulty = models.CharField(
        max_length=20,
        help_text=_("Difficulty level at time of session"),
    )
    language = models.CharField(
        max_length=20,
        choices=CodingChallenge.Language.choices,
        help_text=_("Programming language"),
    )

    # User's work
    user_code = models.TextField(
        blank=True,
        help_text=_("The user's current code"),
    )
    hints_used = models.PositiveIntegerField(
        default=0,
        help_text=_("Number of hints revealed"),
    )

    # Progress tracking
    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.IN_PROGRESS,
        db_index=True,
        help_text=_("Current status of the session"),
    )

    # Timestamps
    started_at = models.DateTimeField(auto_now_add=True)
    submitted_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text=_("When the code was submitted"),
    )
    completed_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text=_("When evaluation was completed"),
    )

    class Meta:
        ordering = ["-started_at"]
        verbose_name = _("Coding Session")
        verbose_name_plural = _("Coding Sessions")
        indexes = [
            models.Index(fields=["user", "status"]),
            models.Index(fields=["subject", "status"]),
        ]

    def __str__(self) -> str:
        return f"{self.user.username} - {self.challenge.title} ({self.started_at:%Y-%m-%d})"

    def get_absolute_url(self) -> str:
        """Return the URL for this coding session."""
        return reverse(
            "coding:challenge",
            kwargs={"subject_slug": self.subject.slug, "pk": self.pk},
        )

    @property
    def is_complete(self) -> bool:
        """Check if the session has been completed."""
        return self.status == self.Status.COMPLETED

    @property
    def time_spent_seconds(self) -> int | None:
        """Calculate time spent on the challenge."""
        if self.submitted_at:
            delta = self.submitted_at - self.started_at
            return int(delta.total_seconds())
        return None


class CodingResponse(models.Model):
    """
    Stores a user's code submission and Claude's evaluation.

    Each session may have multiple responses if resubmission is allowed,
    but typically one final evaluation per session.
    """

    # Relationship
    session = models.ForeignKey(
        CodingSession,
        on_delete=models.CASCADE,
        related_name="responses",
        help_text=_("The session this response belongs to"),
    )

    # Submission
    submitted_code = models.TextField(
        help_text=_("The code submitted for evaluation"),
    )
    submission_number = models.PositiveIntegerField(
        default=1,
        help_text=_("Attempt number (if multiple submissions allowed)"),
    )

    # Claude's evaluation
    is_correct = models.BooleanField(
        null=True,
        help_text=_("Whether the solution is functionally correct"),
    )
    overall_score = models.PositiveIntegerField(
        null=True,
        help_text=_("Overall score out of 100"),
    )

    # Detailed feedback (stored as JSON)
    evaluation_result = models.JSONField(
        default=dict,
        help_text=_("Full evaluation result from Claude"),
    )

    # Individual category scores
    correctness_score = models.PositiveIntegerField(
        null=True,
        help_text=_("Score for functional correctness (0-100)"),
    )
    style_score = models.PositiveIntegerField(
        null=True,
        help_text=_("Score for code style/conventions (0-100)"),
    )
    completeness_score = models.PositiveIntegerField(
        null=True,
        help_text=_("Score for completeness of solution (0-100)"),
    )
    efficiency_score = models.PositiveIntegerField(
        null=True,
        help_text=_("Score for algorithmic efficiency (0-100)"),
    )

    # Feedback text
    summary_feedback = models.TextField(
        blank=True,
        help_text=_("High-level summary of the evaluation"),
    )
    detailed_feedback = models.TextField(
        blank=True,
        help_text=_("Detailed explanation of issues and suggestions"),
    )
    areas_for_improvement = models.JSONField(
        default=list,
        help_text=_("List of specific areas to improve"),
    )
    strengths = models.JSONField(
        default=list,
        help_text=_("List of things done well"),
    )

    # Timestamps
    submitted_at = models.DateTimeField(auto_now_add=True)
    evaluated_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text=_("When evaluation was completed"),
    )

    class Meta:
        ordering = ["-submitted_at"]
        verbose_name = _("Coding Response")
        verbose_name_plural = _("Coding Responses")
        indexes = [
            models.Index(fields=["session", "submission_number"]),
        ]

    def __str__(self) -> str:
        status = (
            "Correct"
            if self.is_correct
            else "Incorrect"
            if self.is_correct is False
            else "Pending"
        )
        return f"Submission #{self.submission_number}: {status}"

    @property
    def has_evaluation(self) -> bool:
        """Check if this response has been evaluated."""
        return self.evaluated_at is not None
