# Generated by Django 6.0.3 on 2026-03-03 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("questions", "0001_initial"),
        ("subjects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LightningSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        default="intermediate",
                        help_text="Difficulty level for questions",
                        max_length=20,
                    ),
                ),
                (
                    "time_limit_seconds",
                    models.PositiveIntegerField(
                        choices=[
                            (60, "1 minute"),
                            (120, "2 minutes"),
                            (180, "3 minutes"),
                            (300, "5 minutes"),
                            (600, "10 minutes"),
                            (900, "15 minutes"),
                        ],
                        default=300,
                        help_text="Time limit in seconds",
                    ),
                ),
                (
                    "questions_answered",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of questions answered"
                    ),
                ),
                (
                    "questions_correct",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of correct answers"
                    ),
                ),
                (
                    "current_streak",
                    models.PositiveIntegerField(
                        default=0, help_text="Current consecutive correct answers"
                    ),
                ),
                (
                    "best_streak",
                    models.PositiveIntegerField(
                        default=0, help_text="Best streak achieved in this session"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("timed_out", "Timed Out"),
                        ],
                        db_index=True,
                        default="in_progress",
                        help_text="Current status of the session",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the session ended", null=True
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="The subject area for this lightning round",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lightning_sessions",
                        to="subjects.subject",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user taking this lightning round",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lightning_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lightning Session",
                "verbose_name_plural": "Lightning Sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="LightningAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_answer",
                    models.CharField(
                        help_text="The user's answer (option letter)", max_length=10
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(help_text="Whether the answer was correct"),
                ),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "response_time_ms",
                    models.PositiveIntegerField(
                        default=0, help_text="Time taken to answer in milliseconds"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        help_text="The question that was answered",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lightning_answers",
                        to="questions.question",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        help_text="The lightning session this answer belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="lightning.lightningsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lightning Answer",
                "verbose_name_plural": "Lightning Answers",
                "ordering": ["answered_at"],
            },
        ),
    ]
