# Generated by Django 6.0.3 on 2026-03-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lightning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lightningsession",
            name="interview_question_pool",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Pre-ranked question IDs for interview mode (empty for other modes)",
            ),
        ),
    ]
