# Generated by Django 6.0.3 on 2026-03-04 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("subjects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyStreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_streak",
                    models.PositiveIntegerField(
                        default=0, help_text="Current consecutive days of study"
                    ),
                ),
                (
                    "longest_streak",
                    models.PositiveIntegerField(
                        default=0, help_text="Longest streak ever achieved"
                    ),
                ),
                (
                    "last_activity_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of most recent study activity",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The user this streak belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_streak",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Study Streak",
                "verbose_name_plural": "Study Streaks",
            },
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exam_sessions",
                    models.PositiveIntegerField(
                        default=0, help_text="Total completed exam sessions"
                    ),
                ),
                (
                    "exam_correct",
                    models.PositiveIntegerField(
                        default=0, help_text="Total correct answers in exams"
                    ),
                ),
                (
                    "exam_total",
                    models.PositiveIntegerField(
                        default=0, help_text="Total questions answered in exams"
                    ),
                ),
                (
                    "lightning_sessions",
                    models.PositiveIntegerField(
                        default=0, help_text="Total completed lightning sessions"
                    ),
                ),
                (
                    "lightning_correct",
                    models.PositiveIntegerField(
                        default=0, help_text="Total correct answers in lightning rounds"
                    ),
                ),
                (
                    "lightning_total",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total questions answered in lightning rounds",
                    ),
                ),
                (
                    "lightning_best_streak",
                    models.PositiveIntegerField(
                        default=0, help_text="Best streak achieved in lightning rounds"
                    ),
                ),
                (
                    "qa_sessions",
                    models.PositiveIntegerField(
                        default=0, help_text="Total Q&A sessions started"
                    ),
                ),
                (
                    "last_studied_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this subject was last studied",
                        null=True,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="The subject area for this progress",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="subjects.subject",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user this progress belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Progress",
                "verbose_name_plural": "User Progress Records",
                "ordering": ["-last_studied_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-last_studied_at"],
                        name="accounts_us_user_id_9ae838_idx",
                    )
                ],
                "unique_together": {("user", "subject")},
            },
        ),
    ]
