# Generated by Django 6.0.3 on 2026-03-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprogress",
            name="argument_avg_focus",
            field=models.FloatField(
                default=0.0, help_text="Average topic focus score (1-10)"
            ),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="argument_avg_technical",
            field=models.FloatField(
                default=0.0, help_text="Average technical accuracy score (1-10)"
            ),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="argument_avg_temperament",
            field=models.FloatField(
                default=0.0, help_text="Average temperament control score (1-10)"
            ),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="argument_sessions",
            field=models.PositiveIntegerField(
                default=0, help_text="Total completed argument sessions"
            ),
        ),
    ]
