# Generated by Django 6.0.3 on 2026-03-03 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("subjects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QASession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated or user-provided session title",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("archived", "Archived")],
                        db_index=True,
                        default="active",
                        help_text="Session status",
                        max_length=20,
                    ),
                ),
                (
                    "message_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of messages in this session"
                    ),
                ),
                (
                    "total_tokens_estimate",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Estimated total tokens used (4 chars = 1 token)",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_message_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of most recent message",
                        null=True,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="The subject area for this conversation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qa_sessions",
                        to="subjects.subject",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who owns this session",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qa_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Q&A Session",
                "verbose_name_plural": "Q&A Sessions",
                "ordering": ["-last_message_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")],
                        help_text="Who sent this message",
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Message content (markdown supported)"),
                ),
                (
                    "token_count_estimate",
                    models.PositiveIntegerField(
                        default=0, help_text="Estimated token count (4 chars ≈ 1 token)"
                    ),
                ),
                (
                    "quick_action",
                    models.CharField(
                        blank=True,
                        help_text="If generated by quick action button (e.g., 'explain_further')",
                        max_length=50,
                    ),
                ),
                (
                    "reference_message_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="ID of message this is in reference to (for quick actions)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "session",
                    models.ForeignKey(
                        help_text="The session this message belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="qanda.qasession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="qasession",
            index=models.Index(
                fields=["user", "status"], name="qanda_qases_user_id_537863_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qasession",
            index=models.Index(
                fields=["subject", "status"], name="qanda_qases_subject_526731_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["session", "created_at"], name="qanda_messa_session_32fd61_idx"
            ),
        ),
    ]
