# Generated by Django 6.0.3 on 2026-03-07 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subjects", "0002_subject_coding_language"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MathProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "problem_type",
                    models.CharField(
                        choices=[
                            ("complete", "Complete the Equation"),
                            ("solve", "Solve from Scratch"),
                            ("mc", "Multiple Choice"),
                        ],
                        db_index=True,
                        default="complete",
                        help_text="Type of problem",
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        db_index=True,
                        default="intermediate",
                        help_text="Difficulty level",
                        max_length=20,
                    ),
                ),
                (
                    "problem_text",
                    models.TextField(help_text="Plain text description of the problem"),
                ),
                (
                    "problem_latex",
                    models.TextField(help_text="The equation/problem in LaTeX format"),
                ),
                (
                    "blank_placeholder",
                    models.CharField(
                        blank=True,
                        default="_____",
                        help_text="Placeholder text for the blank (for complete type)",
                        max_length=50,
                    ),
                ),
                (
                    "correct_answer_latex",
                    models.TextField(help_text="The correct answer in LaTeX format"),
                ),
                (
                    "acceptable_alternatives",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Alternative correct forms in LaTeX",
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Answer options as LaTeX strings (for MC type)",
                    ),
                ),
                (
                    "correct_option",
                    models.CharField(
                        blank=True,
                        help_text="The correct option letter (A, B, C, D) for MC type",
                        max_length=1,
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        help_text="Specific topic (e.g., 'Bellman Equation', 'Policy Gradient')",
                        max_length=100,
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True, help_text="Explanation of the correct answer"
                    ),
                ),
                (
                    "hints",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Progressive hints for the problem",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text="Tags for categorization"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manually Created"),
                            ("claude_api", "Claude API Generated"),
                        ],
                        db_index=True,
                        default="manual",
                        help_text="How this problem was created",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this problem is available for use",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="The subject area this problem belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="math_problems",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Math Problem",
                "verbose_name_plural": "Math Problems",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MathSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        help_text="Difficulty level for this session",
                        max_length=20,
                    ),
                ),
                (
                    "problem_types",
                    models.JSONField(
                        default=list,
                        help_text="Selected problem types for this session",
                    ),
                ),
                (
                    "topic_filter",
                    models.CharField(
                        blank=True, help_text="Optional topic filter", max_length=100
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        db_index=True,
                        default="in_progress",
                        help_text="Current status of the session",
                        max_length=20,
                    ),
                ),
                (
                    "current_problem_index",
                    models.PositiveIntegerField(
                        default=0, help_text="Index of current problem (0-based)"
                    ),
                ),
                (
                    "total_problems",
                    models.PositiveIntegerField(
                        default=10, help_text="Total number of problems in this session"
                    ),
                ),
                (
                    "score",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of problems answered correctly"
                    ),
                ),
                (
                    "total_points",
                    models.FloatField(
                        default=0.0, help_text="Total points including partial credit"
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the session was completed",
                        null=True,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="The subject area for this session",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="math_sessions",
                        to="subjects.subject",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user taking this session",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="math_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Math Session",
                "verbose_name_plural": "Math Sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="MathAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_answer_latex",
                    models.TextField(help_text="The user's answer in LaTeX format"),
                ),
                (
                    "selected_option",
                    models.CharField(
                        blank=True,
                        help_text="Selected option for MC problems (A, B, C, D)",
                        max_length=1,
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        help_text="Whether the answer is fully correct", null=True
                    ),
                ),
                (
                    "partial_credit",
                    models.FloatField(
                        blank=True,
                        help_text="Partial credit score (0.0 to 1.0)",
                        null=True,
                    ),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True, help_text="Feedback from Claude on the answer"
                    ),
                ),
                (
                    "mathematical_errors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of specific mathematical errors identified",
                    ),
                ),
                (
                    "hints_used",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of hints the user revealed"
                    ),
                ),
                (
                    "time_taken_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Time taken to answer in seconds",
                        null=True,
                    ),
                ),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "evaluated_at",
                    models.DateTimeField(
                        blank=True, help_text="When the answer was evaluated", null=True
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        help_text="The problem being answered",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="equations.mathproblem",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        help_text="The session this answer belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="equations.mathsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Math Answer",
                "verbose_name_plural": "Math Answers",
                "ordering": ["answered_at"],
            },
        ),
        migrations.CreateModel(
            name="MathSessionProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of this problem in the session"
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="equations.mathproblem",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_problems",
                        to="equations.mathsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session Problem",
                "verbose_name_plural": "Session Problems",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="mathsession",
            name="problems",
            field=models.ManyToManyField(
                related_name="sessions",
                through="equations.MathSessionProblem",
                to="equations.mathproblem",
            ),
        ),
        migrations.AddIndex(
            model_name="mathproblem",
            index=models.Index(
                fields=["subject", "difficulty", "is_active"],
                name="equations_m_subject_b31243_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mathproblem",
            index=models.Index(
                fields=["subject", "problem_type", "is_active"],
                name="equations_m_subject_344a38_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mathanswer",
            index=models.Index(
                fields=["session", "problem"], name="equations_m_session_b11c02_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mathsessionproblem",
            unique_together={("session", "order")},
        ),
        migrations.AddIndex(
            model_name="mathsession",
            index=models.Index(
                fields=["user", "status"], name="equations_m_user_id_d3a999_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mathsession",
            index=models.Index(
                fields=["subject", "status"], name="equations_m_subject_8d296d_idx"
            ),
        ),
    ]
