# Generated by Django 6.0.3 on 2026-03-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mathsession",
            name="llm_provider",
            field=models.CharField(
                default="openai",
                help_text="LLM provider for AI evaluation (claude or openai)",
                max_length=20,
            ),
        ),
    ]
