# Generated by Django 6.0.3 on 2026-09-29 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField()),
                (
                    "period_end",
                    models.DateField(
                        help_text="Inclusive: the last day the invoice covers"
                    ),
                ),
                ("subtotal_cents", models.IntegerField(default=0)),
                ("total_cents", models.IntegerField(default=0)),
                ("line_item_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("issued", "Issued"),
                            ("paid", "Paid"),
                            ("void", "Void"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-period_end"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "period_start", "period_end"),
                        name="unique_invoice_period_per_tenant",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("seat", "Seat"),
                            ("storage", "Storage"),
                            ("api_call", "API call"),
                            ("support", "Support"),
                            ("credit", "Credit"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                (
                    "amount_cents",
                    models.IntegerField(help_text="Negative for credits and refunds"),
                ),
                ("created_at", models.DateTimeField(db_index=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="line_items",
                        to="projects.project",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "created_at"],
                        name="billing_lin_tenant__d37700_idx",
                    )
                ],
            },
        ),
    ]
