# Generated by Django 6.0.3 on 2026-03-05 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadinessSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_level",
                    models.CharField(
                        choices=[
                            ("entry", "Entry-level"),
                            ("senior", "Senior"),
                            ("principal", "Principal"),
                        ],
                        default="entry",
                        help_text="Target role level for this assessment",
                        max_length=20,
                    ),
                ),
                (
                    "overall_score",
                    models.FloatField(help_text="Weighted composite score (0-100)"),
                ),
                (
                    "is_ready",
                    models.BooleanField(help_text="Meets threshold for target role"),
                ),
                (
                    "coding_score",
                    models.FloatField(help_text="Coding mode score (0-100)", null=True),
                ),
                (
                    "exam_score",
                    models.FloatField(help_text="Exam mode score (0-100)", null=True),
                ),
                (
                    "argument_score",
                    models.FloatField(
                        help_text="Argument mode score (0-100)", null=True
                    ),
                ),
                (
                    "lightning_score",
                    models.FloatField(
                        help_text="Lightning mode score (0-100)", null=True
                    ),
                ),
                (
                    "category_scores",
                    models.JSONField(
                        default=dict,
                        help_text="Score per required category: {category_name: score}",
                    ),
                ),
                (
                    "category_coverage",
                    models.JSONField(
                        default=dict,
                        help_text="Coverage per category: {category_name: {subjects_attempted, subjects_required, is_covered}}",
                    ),
                ),
                (
                    "difficulty_scores",
                    models.JSONField(
                        default=dict,
                        help_text="{difficulty_level: {correct, total, accuracy}}",
                    ),
                ),
                (
                    "assessment_period_start",
                    models.DateField(help_text="Start of the assessment period"),
                ),
                (
                    "assessment_period_end",
                    models.DateField(help_text="End of the assessment period"),
                ),
                (
                    "sessions_in_period",
                    models.PositiveIntegerField(
                        help_text="Number of sessions completed in the assessment period"
                    ),
                ),
                (
                    "recommendations",
                    models.JSONField(
                        default=list, help_text="List of study recommendations"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user this assessment belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readiness_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Readiness Snapshot",
                "verbose_name_plural": "Readiness Snapshots",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="readiness_r_user_id_47d0ec_idx",
                    ),
                    models.Index(
                        fields=["user", "role_level", "-created_at"],
                        name="readiness_r_user_id_abb220_idx",
                    ),
                ],
            },
        ),
    ]
