# Generated by Django 6.0.3 on 2026-03-03 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_text",
                    models.TextField(
                        help_text="The question text (may include code snippets)"
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[("mc", "Multiple Choice"), ("free", "Free Text")],
                        default="mc",
                        help_text="Type of question: multiple choice or free text",
                        max_length=10,
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of answer options for multiple choice questions",
                    ),
                ),
                (
                    "correct_answer",
                    models.TextField(
                        help_text="The correct answer (option letter for MC, full text for free)"
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True, help_text="Explanation of why the answer is correct"
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        db_index=True,
                        default="intermediate",
                        help_text="Difficulty level of the question",
                        max_length=20,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags for categorizing the question",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("llm_studying", "LLM Studying Files"),
                            ("claude_api", "Claude API Generated"),
                            ("manual", "Manually Created"),
                        ],
                        db_index=True,
                        default="claude_api",
                        help_text="Where this question originated from",
                        max_length=20,
                    ),
                ),
                (
                    "source_file",
                    models.CharField(
                        blank=True,
                        help_text="Path to source file (for llm_studying questions)",
                        max_length=500,
                    ),
                ),
                (
                    "source_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Hash of source content for deduplication",
                        max_length=64,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this question is available for use",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="The subject area this question belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["subject", "difficulty", "is_active"],
                        name="questions_q_subject_a813cc_idx",
                    ),
                    models.Index(
                        fields=["subject", "question_type", "is_active"],
                        name="questions_q_subject_2d0db2_idx",
                    ),
                ],
            },
        ),
    ]
