# Generated by Django 6.0.3 on 2026-03-04 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0001_initial"),
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Document title (usually the file name)",
                        max_length=255,
                    ),
                ),
                ("content", models.TextField(help_text="Full document content")),
                (
                    "source_file",
                    models.CharField(
                        blank=True, help_text="Original file path", max_length=500
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 hash of content for deduplication",
                        max_length=64,
                    ),
                ),
                (
                    "token_estimate",
                    models.PositiveIntegerField(
                        default=0, help_text="Estimated token count (len/4)"
                    ),
                ),
                (
                    "questions_generated",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of questions generated from this material",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this material is available for use",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="The subject area this material belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_materials",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Study Material",
                "verbose_name_plural": "Study Materials",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["subject", "is_active"],
                        name="questions_s_subject_5f15ed_idx",
                    )
                ],
                "unique_together": {("subject", "content_hash")},
            },
        ),
    ]
