# Generated by Django 6.0.3 on 2026-03-04 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("subjects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VisualTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Display title for the visual topic", max_length=200
                    ),
                ),
                (
                    "slug",
                    models.SlugField(help_text="URL-safe identifier", max_length=200),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Brief description shown in topic picker"
                    ),
                ),
                (
                    "rendering_type",
                    models.CharField(
                        choices=[
                            ("mermaid", "Mermaid.js (Flowcharts/Trees)"),
                            ("d3", "D3.js (Custom Interactive)"),
                            ("static", "Static Image/SVG"),
                            ("code", "Code Evolution"),
                        ],
                        default="mermaid",
                        help_text="How to render the diagram",
                        max_length=20,
                    ),
                ),
                (
                    "steps",
                    models.JSONField(
                        default=list,
                        help_text="Array of step objects: [{step_number, title, explanation, diagram_data}, ...]",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        default="intermediate",
                        help_text="Difficulty level of the concept",
                        max_length=20,
                    ),
                ),
                (
                    "estimated_time_minutes",
                    models.PositiveIntegerField(
                        default=5, help_text="Estimated time to complete the visual"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(default=list, help_text="Related topic tags"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="manual",
                        help_text="How this visual was created (manual, claude_api)",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="The subject this visual belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visual_topics",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visual Topic",
                "verbose_name_plural": "Visual Topics",
                "ordering": ["subject", "title"],
            },
        ),
        migrations.CreateModel(
            name="VisualSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_step",
                    models.PositiveIntegerField(
                        default=0, help_text="Current step index (0-indexed)"
                    ),
                ),
                (
                    "max_step_reached",
                    models.PositiveIntegerField(
                        default=0, help_text="Highest step index the user has viewed"
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(
                        default=False, help_text="Whether the user has viewed all steps"
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_viewed_at", models.DateTimeField(auto_now=True)),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the user completed all steps",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user viewing this visual",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visual_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visual_topic",
                    models.ForeignKey(
                        help_text="The visual topic being viewed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="visuals.visualtopic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visual Session",
                "verbose_name_plural": "Visual Sessions",
                "ordering": ["-last_viewed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="visualtopic",
            index=models.Index(
                fields=["subject", "status"], name="visuals_vis_subject_ae02a5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="visualtopic",
            unique_together={("subject", "slug")},
        ),
        migrations.AddIndex(
            model_name="visualsession",
            index=models.Index(
                fields=["user", "completed"], name="visuals_vis_user_id_c56146_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="visualsession",
            unique_together={("user", "visual_topic")},
        ),
    ]
