# Generated by Django 6.0.3 on 2026-03-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExamAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_answer",
                    models.TextField(
                        blank=True,
                        help_text="The user's answer (option letter for MC, text for free)",
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        help_text="Whether the answer was correct (null if not yet answered)",
                        null=True,
                    ),
                ),
                (
                    "is_flagged",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user flagged this question for review",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of this question in the exam"
                    ),
                ),
                (
                    "answered_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this question was answered",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Answer",
                "verbose_name_plural": "Exam Answers",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ExamSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        default="intermediate",
                        help_text="Difficulty level selected for this exam",
                        max_length=20,
                    ),
                ),
                (
                    "question_count",
                    models.PositiveIntegerField(
                        default=10, help_text="Number of questions in this exam"
                    ),
                ),
                (
                    "current_question_index",
                    models.PositiveIntegerField(
                        default=0, help_text="Index of the current question (0-based)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        db_index=True,
                        default="in_progress",
                        help_text="Current status of the exam session",
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of correct answers"
                    ),
                ),
                (
                    "total_answered",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of questions answered"
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the exam was completed", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Session",
                "verbose_name_plural": "Exam Sessions",
                "ordering": ["-started_at"],
            },
        ),
    ]
