# Generated by Django 6.0.3 on 2026-03-03 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("exam", "0001_initial"),
        ("questions", "0001_initial"),
        ("subjects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="examanswer",
            name="question",
            field=models.ForeignKey(
                help_text="The question being answered",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_answers",
                to="questions.question",
            ),
        ),
        migrations.AddField(
            model_name="examsession",
            name="questions",
            field=models.ManyToManyField(
                help_text="Questions included in this exam",
                related_name="exam_sessions",
                through="exam.ExamAnswer",
                to="questions.question",
            ),
        ),
        migrations.AddField(
            model_name="examsession",
            name="subject",
            field=models.ForeignKey(
                help_text="The subject area for this exam",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_sessions",
                to="subjects.subject",
            ),
        ),
        migrations.AddField(
            model_name="examsession",
            name="user",
            field=models.ForeignKey(
                help_text="The user taking this exam",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="examanswer",
            name="session",
            field=models.ForeignKey(
                help_text="The exam session this answer belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="exam.examsession",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="examanswer",
            unique_together={("session", "question")},
        ),
    ]
