# Generated by Django 6.0.3 on 2026-03-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="examsession",
            name="is_practice",
            field=models.BooleanField(
                default=False,
                help_text="Practice mode - results won't affect your statistics",
            ),
        ),
    ]
