#!/usr/bin/env python3
"""Generate the two-tenant seed data.

**The two tenants' rows are deliberately indistinguishable by content.** Same customer
names, same email local-parts, same SKUs, same product names, the same order ids, the
same order totals. The only thing that differs is ``tenant_id``.

That is the whole design. A cross-tenant leak in a fixture where ACME sells kayaks and
BORG sells industrial lubricant is obvious from one glance at the output, so every test
written against it accidentally passes for the wrong reason -- the author sees sensible
rows and moves on. Make the data identical and a leak has exactly one signature: the row
count doubles, and ``tenant_id`` is the only column that says so.

Which gives every isolation test the same crisp assertion:

    scoped   -> 20 orders, all tenant_id = 'acme'
    leaking  -> 40 orders, two distinct tenant_ids

Deterministic by construction: no RNG at all, just arithmetic over fixed lists. Both the
generator and its output are committed, so a reviewer can read the SQL and a sceptic can
regenerate it.
"""

from __future__ import annotations

import argparse
from datetime import datetime, timedelta, timezone
from pathlib import Path

#: The two tenants. ACME is "us" in every test; BORG is the one whose rows must never
#: appear in an answer.
TENANTS = [("acme", "Acme Corporation", "growth"), ("borg", "Borg Industries", "enterprise")]

#: API keys, stored as sha256 hashes. The plaintext is in the README and in .env.example
#: because this is a development fixture and pretending otherwise helps nobody.
API_KEYS = {"acme": "acme-dev-key", "borg": "borg-dev-key"}

#: A key that was rotated out. Seeded deliberately: "revoked" is a state the
#: authentication path has to handle, and a fixture set with no revoked key cannot tell
#: a service that checks revoked_at from one that ignores it.
REVOKED_KEYS = {"acme": "acme-retired-key"}

#: Identical across both tenants, on purpose. See the module docstring.
CUSTOMERS = [
    (1, "Dana Whitfield", "dana", "GB"),
    (2, "Oluwaseun Ajayi", "seun", "NG"),
    (3, "Marta Kowalski", "marta", "PL"),
    (4, "Hiroshi Tanaka", "hiroshi", "JP"),
    (5, "Camila Rojas", "camila", "CL"),
    (6, "Ted Brennan", "ted", "IE"),
]

PRODUCTS = [
    (1, "SKU-100", "Trail Pack 40L", "Outdoor", 12900),
    (2, "SKU-101", "Stove Kit", "Outdoor", 6400),
    (3, "SKU-200", "Desk Lamp", "Home", 3900),
    (4, "SKU-201", "Chair Mat", "Home", 5500),
    (5, "SKU-300", "Cable Set", "Accessories", 1900),
]

STATUSES = ["paid", "paid", "paid", "pending", "refunded"]

#: Anchored, not relative to now, so a test asserting on a date range does not start
#: failing at midnight on the first of the month.
EPOCH = datetime(2026, 1, 5, 9, 0, tzinfo=timezone.utc)

ORDERS_PER_TENANT = 20


def sha256_hex(value: str) -> str:
    """Return the hex sha256 of a string."""
    import hashlib

    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def quote(value: str) -> str:
    """Quote a SQL string literal, doubling any embedded quote."""
    escaped = value.replace("'", "''")
    return f"'{escaped}'"


def generate() -> str:
    """Render the whole seed as one idempotent SQL script."""
    lines: list[str] = [
        "-- Generated by tools/gen_seed_data.py. Do not edit by hand.",
        "--",
        "-- Two tenants whose rows are identical except for tenant_id, so that a",
        "-- cross-tenant leak shows up as a doubled row count rather than as data a",
        "-- reader has to notice looks wrong.",
        "",
        "BEGIN;",
        "",
    ]

    for tenant_id, name, plan in TENANTS:
        lines.append(
            f"INSERT INTO tenants (id, name, plan_code) VALUES "
            f"({quote(tenant_id)}, {quote(name)}, {quote(plan)}) "
            f"ON CONFLICT (id) DO NOTHING;"
        )
    lines.append("")

    for tenant_id, _, _ in TENANTS:
        digest = sha256_hex(API_KEYS[tenant_id])
        lines.append(
            f"INSERT INTO api_keys (key_sha256, tenant_id, label) VALUES "
            f"({quote(digest)}, {quote(tenant_id)}, {quote('dev key')}) "
            f"ON CONFLICT (key_sha256) DO NOTHING;"
        )
    for tenant_id, raw in REVOKED_KEYS.items():
        digest = sha256_hex(raw)
        lines.append(
            f"INSERT INTO api_keys (key_sha256, tenant_id, label, revoked_at) VALUES "
            f"({quote(digest)}, {quote(tenant_id)}, {quote('rotated out')}, "
            f"{quote('2026-02-01T00:00:00+00:00')}) ON CONFLICT (key_sha256) DO NOTHING;"
        )
    lines.append("")

    for tenant_id, _, _ in TENANTS:
        for cid, cname, local, country in CUSTOMERS:
            email = f"{local}@{tenant_id}.example"
            lines.append(
                f"INSERT INTO customers (id, tenant_id, name, email, country) VALUES "
                f"({cid}, {quote(tenant_id)}, {quote(cname)}, {quote(email)}, "
                f"{quote(country)}) ON CONFLICT DO NOTHING;"
            )
        lines.append("")

        for pid, sku, pname, category, price in PRODUCTS:
            lines.append(
                f"INSERT INTO products (id, tenant_id, sku, name, category, price_cents) "
                f"VALUES ({pid}, {quote(tenant_id)}, {quote(sku)}, {quote(pname)}, "
                f"{quote(category)}, {price}) ON CONFLICT DO NOTHING;"
            )
        lines.append("")

        item_id = 0
        for order_id in range(1, ORDERS_PER_TENANT + 1):
            customer_id = (order_id % len(CUSTOMERS)) + 1
            status = STATUSES[order_id % len(STATUSES)]
            placed = EPOCH + timedelta(days=order_id * 4, hours=order_id % 7)
            # Two line items per order, chosen by arithmetic so the totals are
            # reproducible and can be checked by hand.
            first = PRODUCTS[order_id % len(PRODUCTS)]
            second = PRODUCTS[(order_id + 2) % len(PRODUCTS)]
            quantities = (1 + order_id % 3, 1 + (order_id + 1) % 2)
            total = first[4] * quantities[0] + second[4] * quantities[1]

            lines.append(
                f"INSERT INTO orders (id, tenant_id, customer_id, status, total_cents, "
                f"placed_at) VALUES ({order_id}, {quote(tenant_id)}, {customer_id}, "
                f"{quote(status)}, {total}, {quote(placed.isoformat())}) "
                f"ON CONFLICT DO NOTHING;"
            )
            for product, quantity in zip((first, second), quantities, strict=True):
                item_id += 1
                lines.append(
                    f"INSERT INTO order_items (id, tenant_id, order_id, product_id, "
                    f"quantity, unit_cents) VALUES ({item_id}, {quote(tenant_id)}, "
                    f"{order_id}, {product[0]}, {quantity}, {product[4]}) "
                    f"ON CONFLICT DO NOTHING;"
                )
        lines.append("")

    lines.append("COMMIT;")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    """Write the seed script."""
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--out", type=Path, default=Path("db/seed.sql"))
    args = parser.parse_args(argv)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(generate(), encoding="utf-8")
    print(
        f"wrote {args.out}: {len(TENANTS)} tenants, "
        f"{len(CUSTOMERS) * len(TENANTS)} customers, "
        f"{ORDERS_PER_TENANT * len(TENANTS)} orders"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
