# Generated by Django 6.0.3 on 2026-09-29 22:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("subjects", "0005_subject_supports_systemdesign"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exercise_number",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        help_text="Stable 1-50 number, used in the on-disk directory name",
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL and directory identifier, e.g. 'ex-017-tenant-isolation'",
                        max_length=120,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Shown in the catalog, phrased as a ticket title",
                        max_length=200,
                    ),
                ),
                (
                    "exercise_type",
                    models.CharField(
                        choices=[
                            ("critical_bug", "Fix a critical bug fast"),
                            ("latency", "Fix a severe latency issue"),
                            ("ml_deploy", "Implement and deploy an ML model"),
                            ("etl_pipeline", "Build or fix a data/ETL pipeline"),
                            ("genai_chatbot", "Fix a generative-AI QA chatbot"),
                            (
                                "eda_library",
                                "Build or fix an EDA/preprocessing library",
                            ),
                            (
                                "tenant_isolation",
                                "Ensure tenant isolation for text-to-SQL",
                            ),
                            (
                                "eval_framework",
                                "Create or fix a genAI evaluation framework",
                            ),
                            (
                                "analytics_features",
                                "Add analytics/statistical features",
                            ),
                            ("cicd_pipeline", "Fix a broken or flaky CI/CD pipeline"),
                        ],
                        db_index=True,
                        help_text="Which of the ten kinds of work this exercise asks for",
                        max_length=30,
                    ),
                ),
                (
                    "base_app",
                    models.CharField(
                        choices=[
                            ("tenantsaas", "Django multi-tenant SaaS (Postgres)"),
                            ("predictsvc", "FastAPI ML prediction service"),
                            ("etlduck", "DuckDB warehouse / ETL pipeline"),
                            ("ragqa", "RAG / generative-AI QA chatbot"),
                            ("sqlgenie", "Text-to-SQL chatbot (multi-tenant Postgres)"),
                            ("eventstore", "MongoDB event store + performance model"),
                            ("edakit", "EDA / data-preprocessing library"),
                        ],
                        db_index=True,
                        help_text="Which base application template this exercise is built on",
                        max_length=30,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        db_index=True,
                        help_text="Driven by how many files must change and how hard they are to find",
                        max_length=20,
                    ),
                ),
                (
                    "defect_class",
                    models.CharField(
                        db_index=True,
                        help_text="Closed-vocabulary defect category, e.g. 'n_plus_one'. Used to enforce variety: no class may appear more than twice across the catalog",
                        max_length=60,
                    ),
                ),
                (
                    "brief_md",
                    models.TextField(help_text="Markdown ticket the user reads before starting"),
                ),
                (
                    "definition_of_done",
                    models.JSONField(
                        default=list,
                        help_text="User-facing checklist; each item maps to a check id or 'llm'",
                    ),
                ),
                (
                    "time_limit_seconds",
                    models.PositiveIntegerField(
                        choices=[
                            (1200, "20 minutes"),
                            (1500, "25 minutes"),
                            (1800, "30 minutes"),
                            (2100, "35 minutes"),
                            (2400, "40 minutes"),
                            (2700, "45 minutes"),
                            (3000, "50 minutes"),
                            (3300, "55 minutes"),
                            (3600, "60 minutes"),
                        ],
                        help_text="Time box, between 20 and 60 minutes",
                        validators=[
                            django.core.validators.MinValueValidator(1200),
                            django.core.validators.MaxValueValidator(3600),
                        ],
                    ),
                ),
                (
                    "expected_time_minutes",
                    models.PositiveIntegerField(
                        help_text="Authored estimate at roughly 60-70% of the limit. The slack is where writing NOTES.md is meant to happen"
                    ),
                ),
                (
                    "focus_paths",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Where the work belongs; orders the diff sent to the grader",
                    ),
                ),
                (
                    "protected_paths",
                    models.JSONField(
                        default=list,
                        help_text="Globs hashed at scaffold time so test tampering is detectable",
                    ),
                ),
                (
                    "mutations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Typed operations that break the pristine template",
                    ),
                ),
                (
                    "grading_spec",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Authored checks, weights and the measured pre-fix baseline",
                    ),
                ),
                (
                    "grading_notes",
                    models.TextField(
                        blank=True,
                        help_text="PRIVATE. Root cause, what a good fix looks like, and common wrong turns. Sent to the grader but never shown to the user",
                    ),
                ),
                (
                    "context_excerpts",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Unchanged code the grader needs in order to judge fit with the codebase",
                    ),
                ),
                (
                    "hints",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Progressive hints; each one costs engineering points",
                    ),
                ),
                (
                    "databases",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Subset of postgres/mongodb/duckdb. RDS is emulated as Postgres plus RDS-shaped artifacts in config, not a distinct backend",
                    ),
                ),
                (
                    "needs_docker",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the exercise requires containers to run",
                    ),
                ),
                (
                    "template_dir",
                    models.CharField(
                        blank=True,
                        help_text="Directory under WORKSPACE_TEMPLATE_ROOT; defaults to base_app",
                        max_length=120,
                    ),
                ),
                (
                    "template_checksum",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 over the template tree, to detect unintended edits",
                        max_length=64,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, help_text="Free-form catalog tags"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether the exercise appears in the catalog",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "primary_subject",
                    models.ForeignKey(
                        blank=True,
                        help_text="For filtering and discovery only. Nothing aggregates by this, which is what keeps subject dashboards meaningful",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workspace_exercises",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "workspace exercise",
                "verbose_name_plural": "workspace exercises",
                "ordering": ["exercise_number"],
            },
        ),
        migrations.CreateModel(
            name="WorkspaceSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exercise_type",
                    models.CharField(
                        choices=[
                            ("critical_bug", "Fix a critical bug fast"),
                            ("latency", "Fix a severe latency issue"),
                            ("ml_deploy", "Implement and deploy an ML model"),
                            ("etl_pipeline", "Build or fix a data/ETL pipeline"),
                            ("genai_chatbot", "Fix a generative-AI QA chatbot"),
                            (
                                "eda_library",
                                "Build or fix an EDA/preprocessing library",
                            ),
                            (
                                "tenant_isolation",
                                "Ensure tenant isolation for text-to-SQL",
                            ),
                            (
                                "eval_framework",
                                "Create or fix a genAI evaluation framework",
                            ),
                            (
                                "analytics_features",
                                "Add analytics/statistical features",
                            ),
                            ("cicd_pipeline", "Fix a broken or flaky CI/CD pipeline"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "time_limit_seconds",
                    models.PositiveIntegerField(
                        help_text="Snapshot of the exercise's limit; the progress bar denominator",
                        validators=[
                            django.core.validators.MinValueValidator(1200),
                            django.core.validators.MaxValueValidator(3600),
                        ],
                    ),
                ),
                ("template_checksum", models.CharField(blank=True, max_length=64)),
                (
                    "workspace_path",
                    models.CharField(
                        blank=True,
                        help_text="Absolute path to the scaffolded repository",
                        max_length=500,
                    ),
                ),
                (
                    "sentinel_written",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the deletion-guard sentinel file was written successfully",
                    ),
                ),
                (
                    "seed_commit_sha",
                    models.CharField(
                        blank=True,
                        help_text="The scaffold commit; the base for every diff taken at submit time",
                        max_length=40,
                    ),
                ),
                (
                    "origin_path",
                    models.CharField(
                        blank=True,
                        help_text="Bare repository that emulates GitHub for push/pull/fetch",
                        max_length=500,
                    ),
                ),
                (
                    "compose_project",
                    models.CharField(
                        blank=True,
                        help_text="COMPOSE_PROJECT_NAME, isolating this exercise's containers",
                        max_length=64,
                    ),
                ),
                (
                    "host_ports",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Service name to allocated host port, e.g. {'postgres': 55123}",
                    ),
                ),
                (
                    "scaffold_log",
                    models.TextField(
                        blank=True,
                        help_text="Step-by-step scaffolding log, shown to the user on failure",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scaffolding", "Scaffolding"),
                            ("ready", "Ready to start"),
                            ("in_progress", "In progress"),
                            ("grading", "Grading"),
                            ("completed", "Completed"),
                            ("timed_out", "Timed out"),
                            ("abandoned", "Abandoned"),
                            ("failed", "Failed to set up"),
                        ],
                        db_index=True,
                        default="scaffolding",
                        max_length=20,
                    ),
                ),
                (
                    "end_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("submitted", "Submitted"),
                            ("timed_out", "Ran out of time"),
                            ("abandoned", "Abandoned by the user"),
                            ("reaped", "Closed automatically after the deadline"),
                            ("failed", "Setup failed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Set explicitly when the user starts the clock, NOT on row creation, so scaffolding and container startup do not consume the time box",
                        null=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Absolute deadline. The authority for all time enforcement",
                        null=True,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user_notes",
                    models.TextField(
                        blank=True,
                        help_text="The NOTES.md-style writeup, autosaved and sent to the grader",
                    ),
                ),
                ("hints_used", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        help_text="PROTECT so a graded attempt is never orphaned by a catalog edit",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="workspace.workspaceexercise",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "workspace session",
                "verbose_name_plural": "workspace sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkspaceGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overall_score",
                    models.PositiveSmallIntegerField(
                        help_text="Weighted 0-100 score, after any speed bonus",
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "base_score",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Before any bonus",
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "letter_grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A", "A"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B", "B"),
                            ("B-", "B-"),
                            ("C+", "C+"),
                            ("C", "C"),
                            ("C-", "C-"),
                            ("D+", "D+"),
                            ("D", "D"),
                            ("D-", "D-"),
                            ("F", "F"),
                        ],
                        db_index=True,
                        max_length=2,
                    ),
                ),
                (
                    "uncapped_letter",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A", "A"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B", "B"),
                            ("B-", "B-"),
                            ("C+", "C+"),
                            ("C", "C"),
                            ("C-", "C-"),
                            ("D+", "D+"),
                            ("D", "D"),
                            ("D-", "D-"),
                            ("F", "F"),
                        ],
                        help_text="What the numeric score alone would have earned",
                        max_length=2,
                    ),
                ),
                (
                    "grade_points",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="4.0-scale value, so progress can be averaged numerically",
                        max_digits=3,
                    ),
                ),
                (
                    "dimension_scores",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="correctness / engineering / documentation / completeness, each 0-100",
                    ),
                ),
                (
                    "documentation_breakdown",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="The five documentation sub-scores",
                    ),
                ),
                (
                    "applied_caps",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Gate codes that lowered the grade. Shown to the user, because a letter without its explanation reads as arbitrary",
                    ),
                ),
                (
                    "applied_deductions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Objective deductions applied to engineering quality",
                    ),
                ),
                ("speed_bonus", models.PositiveSmallIntegerField(default=0)),
                (
                    "objective_status",
                    models.CharField(
                        choices=[
                            ("complete", "All checks ran"),
                            ("partial", "Some checks could not run"),
                            ("indeterminate", "Checks could not be run"),
                        ],
                        default="indeterminate",
                        help_text="Whether the machine-checked half of the grade could be determined",
                        max_length=20,
                    ),
                ),
                (
                    "evaluation_degraded",
                    models.BooleanField(
                        default=False,
                        help_text="True when model review was unavailable and the grade is provisional",
                    ),
                ),
                ("summary_feedback", models.TextField(blank=True)),
                ("detailed_feedback", models.TextField(blank=True)),
                ("strengths", models.JSONField(blank=True, default=list)),
                ("areas_for_improvement", models.JSONField(blank=True, default=list)),
                ("what_a_senior_would_have_done", models.TextField(blank=True)),
                ("root_cause_summary", models.TextField(blank=True)),
                ("symptom_patch_suspected", models.BooleanField(default=False)),
                ("rubric_version", models.CharField(blank=True, max_length=20)),
                ("model_used", models.CharField(blank=True, max_length=60)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                (
                    "grading_log",
                    models.TextField(
                        blank=True,
                        help_text="Every command the harness ran, for auditability",
                    ),
                ),
                ("grading_error", models.TextField(blank=True)),
                ("graded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade",
                        to="workspace.workspacesession",
                    ),
                ),
            ],
            options={
                "verbose_name": "workspace grade",
                "verbose_name_plural": "workspace grades",
                "ordering": ["-graded_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkspaceEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("scaffold_started", "Scaffold started"),
                            ("scaffold_ok", "Scaffold succeeded"),
                            ("scaffold_failed", "Scaffold failed"),
                            ("containers_up", "Containers started"),
                            ("containers_failed", "Containers failed to start"),
                            ("begun", "Clock started"),
                            ("hint_revealed", "Hint revealed"),
                            ("workspace_missing", "Workspace directory missing"),
                            ("docker_missing", "Docker unavailable"),
                            ("submitted", "Submitted"),
                            ("timed_out", "Timed out"),
                            ("reaped", "Reaped after the deadline"),
                            ("graded", "Graded"),
                            ("grade_failed", "Grading failed"),
                            ("torn_down", "Workspace torn down"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="workspace.workspacesession",
                    ),
                ),
            ],
            options={
                "verbose_name": "workspace event",
                "verbose_name_plural": "workspace events",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkspaceSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "capture_ok",
                    models.BooleanField(
                        default=True,
                        help_text="False when the workspace was missing or unreadable",
                    ),
                ),
                ("capture_error", models.TextField(blank=True)),
                ("snapshot_ref", models.CharField(blank=True, max_length=120)),
                ("snapshot_sha", models.CharField(blank=True, max_length=40)),
                (
                    "diff_text",
                    models.TextField(blank=True, help_text="The primary grading artifact"),
                ),
                (
                    "diff_numstat",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Complete inventory of changed files. Never truncated, so the grader always knows what it did not see",
                    ),
                ),
                (
                    "full_files",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Whole-file contents for paths grading needs in full",
                    ),
                ),
                ("files_changed", models.PositiveIntegerField(default=0)),
                ("lines_added", models.PositiveIntegerField(default=0)),
                ("lines_deleted", models.PositiveIntegerField(default=0)),
                (
                    "git_log",
                    models.TextField(
                        blank=True,
                        help_text="Commits since the seed, with full bodies not just subjects",
                    ),
                ),
                ("user_commit_count", models.PositiveIntegerField(default=0)),
                ("branches", models.JSONField(blank=True, default=list)),
                ("porcelain_status", models.TextField(blank=True)),
                ("untracked_paths", models.JSONField(blank=True, default=list)),
                (
                    "bundle_path",
                    models.CharField(
                        blank=True,
                        help_text="Archived git bundle of the whole attempt",
                        max_length=500,
                    ),
                ),
                ("capture_bytes", models.PositiveIntegerField(default=0)),
                (
                    "truncated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the diff was trimmed to fit the grading prompt",
                    ),
                ),
                ("truncation_report", models.JSONField(blank=True, default=dict)),
                ("prompt_char_count", models.PositiveIntegerField(default=0)),
                ("sections_truncated", models.JSONField(blank=True, default=list)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission",
                        to="workspace.workspacesession",
                    ),
                ),
            ],
            options={
                "verbose_name": "workspace submission",
                "verbose_name_plural": "workspace submissions",
                "ordering": ["-captured_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkspaceCheckResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "check_id",
                    models.CharField(help_text="Authored id, e.g. 'R1' or 'S2'", max_length=60),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("pytest", "Specific pytest node"),
                            ("pytest_suite", "Whole suite vs baseline"),
                            ("file_unchanged", "Protected file hashes match"),
                            ("benchmark", "Benchmark script metric threshold"),
                            ("metric", "Model/eval metric threshold"),
                            ("cmd", "Command exit code"),
                            ("grep_absent", "Pattern must not appear"),
                            ("grep_present", "Pattern must appear"),
                            ("flake_repeat", "Test passes N/N under CI env"),
                            ("llm", "Delegated to model judgment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("error", "Could not run"),
                            ("timeout", "Timed out"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("passed", models.BooleanField(default=False)),
                ("weight", models.PositiveIntegerField(default=1)),
                ("required", models.BooleanField(default=True)),
                (
                    "stretch",
                    models.BooleanField(
                        default=False,
                        help_text="Passing at least one stretch check is required for A+",
                    ),
                ),
                ("expected", models.TextField(blank=True)),
                ("actual", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                (
                    "output",
                    models.TextField(blank=True, help_text="Truncated raw command output"),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_results",
                        to="workspace.workspacesubmission",
                    ),
                ),
            ],
            options={
                "verbose_name": "workspace check result",
                "verbose_name_plural": "workspace check results",
                "ordering": ["-required", "check_id"],
            },
        ),
        migrations.AddIndex(
            model_name="workspaceexercise",
            index=models.Index(
                fields=["exercise_type", "difficulty", "is_active"],
                name="workspace_w_exercis_9ccdeb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workspaceexercise",
            index=models.Index(
                fields=["base_app", "is_active"], name="workspace_w_base_ap_7423fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspacesession",
            index=models.Index(fields=["user", "status"], name="workspace_w_user_id_6052e9_idx"),
        ),
        migrations.AddIndex(
            model_name="workspacesession",
            index=models.Index(
                fields=["status", "expires_at"], name="workspace_w_status_0fd30c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="workspacesession",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["scaffolding", "ready", "in_progress", "grading"])
                ),
                fields=("user", "exercise"),
                name="one_active_workspace_session_per_exercise",
            ),
        ),
        migrations.AddIndex(
            model_name="workspaceevent",
            index=models.Index(fields=["session", "kind"], name="workspace_w_session_29f072_idx"),
        ),
        migrations.AddIndex(
            model_name="workspacecheckresult",
            index=models.Index(
                fields=["submission", "passed"], name="workspace_w_submiss_5eed5b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="workspacecheckresult",
            constraint=models.UniqueConstraint(
                fields=("submission", "check_id"), name="unique_check_per_submission"
            ),
        ),
    ]
