# Generated by Django 6.0.3 on 2026-09-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspacegrade",
            name="fairness",
            field=models.CharField(
                blank=True,
                choices=[
                    ("too_harsh", "Too harsh"),
                    ("about_right", "About right"),
                    ("too_generous", "Too generous"),
                ],
                db_index=True,
                help_text="Whether the engineer thought this grade was fair",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="workspacegrade",
            name="fairness_note",
            field=models.CharField(
                blank=True, help_text="Optional free text on why", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="workspacegrade",
            name="fairness_recorded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workspaceevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("scaffold_started", "Scaffold started"),
                    ("scaffold_ok", "Scaffold succeeded"),
                    ("scaffold_failed", "Scaffold failed"),
                    ("containers_up", "Containers started"),
                    ("containers_failed", "Containers failed to start"),
                    ("begun", "Clock started"),
                    ("hint_revealed", "Hint revealed"),
                    ("workspace_missing", "Workspace directory missing"),
                    ("docker_missing", "Docker unavailable"),
                    ("submitted", "Submitted"),
                    ("timed_out", "Timed out"),
                    ("reaped", "Reaped after the deadline"),
                    ("graded", "Graded"),
                    ("grade_failed", "Grading failed"),
                    ("fairness_recorded", "Fairness verdict recorded"),
                    ("torn_down", "Workspace torn down"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
