# Generated by Django 6.0.3 on 2026-10-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "workspace",
            "0002_workspacegrade_fairness_workspacegrade_fairness_note_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspaceexercise",
            name="base_app",
            field=models.CharField(
                choices=[
                    ("tenantsaas", "Django multi-tenant SaaS (Postgres)"),
                    ("predictsvc", "FastAPI ML prediction service"),
                    ("etlduck", "DuckDB warehouse / ETL pipeline"),
                    ("ragqa", "RAG / generative-AI QA chatbot"),
                    ("sqlgenie", "Text-to-SQL chatbot (multi-tenant Postgres)"),
                    ("eventstore", "MongoDB event store + performance model"),
                    ("edakit", "EDA / data-preprocessing library"),
                    ("agentdesk", "Support desk with an agentic assistant (Postgres)"),
                ],
                db_index=True,
                help_text="Which base application template this exercise is built on",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="workspaceexercise",
            name="exercise_type",
            field=models.CharField(
                choices=[
                    ("critical_bug", "Fix a critical bug fast"),
                    ("latency", "Fix a severe latency issue"),
                    ("ml_deploy", "Implement and deploy an ML model"),
                    ("etl_pipeline", "Build or fix a data/ETL pipeline"),
                    ("genai_chatbot", "Fix a generative-AI QA chatbot"),
                    ("eda_library", "Build or fix an EDA/preprocessing library"),
                    ("tenant_isolation", "Ensure tenant isolation for text-to-SQL"),
                    ("eval_framework", "Create or fix a genAI evaluation framework"),
                    ("analytics_features", "Add analytics/statistical features"),
                    ("cicd_pipeline", "Fix a broken or flaky CI/CD pipeline"),
                    ("agent_tools", "Fix an agentic tool-calling loop"),
                    ("model_serving", "Fix model-serving memory and admission control"),
                ],
                db_index=True,
                help_text="Which of the ten kinds of work this exercise asks for",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="workspacesession",
            name="exercise_type",
            field=models.CharField(
                choices=[
                    ("critical_bug", "Fix a critical bug fast"),
                    ("latency", "Fix a severe latency issue"),
                    ("ml_deploy", "Implement and deploy an ML model"),
                    ("etl_pipeline", "Build or fix a data/ETL pipeline"),
                    ("genai_chatbot", "Fix a generative-AI QA chatbot"),
                    ("eda_library", "Build or fix an EDA/preprocessing library"),
                    ("tenant_isolation", "Ensure tenant isolation for text-to-SQL"),
                    ("eval_framework", "Create or fix a genAI evaluation framework"),
                    ("analytics_features", "Add analytics/statistical features"),
                    ("cicd_pipeline", "Fix a broken or flaky CI/CD pipeline"),
                    ("agent_tools", "Fix an agentic tool-calling loop"),
                    ("model_serving", "Fix model-serving memory and admission control"),
                ],
                max_length=30,
            ),
        ),
    ]
