# Generated by Django 6.0.3 on 2026-03-05 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subjects", "0002_subject_coding_language"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArgumentSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        help_text="Difficulty level (beginner, intermediate, advanced)",
                        max_length=20,
                    ),
                ),
                (
                    "heat_level",
                    models.CharField(
                        choices=[
                            ("friend", "Friendly Debate"),
                            ("colleague", "Professional Disagreement"),
                            ("jerk", "Aggressive Challenger"),
                        ],
                        default="colleague",
                        help_text="How aggressive the AI opponent should be",
                        max_length=20,
                    ),
                ),
                (
                    "initial_prompt",
                    models.TextField(
                        help_text="The topic or scenario presented to start the argument"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        db_index=True,
                        default="in_progress",
                        help_text="Current status of the argument session",
                        max_length=20,
                    ),
                ),
                (
                    "message_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of messages exchanged"
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the argument was ended", null=True
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="The subject area for this argument",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="argument_sessions",
                        to="subjects.subject",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user participating in this argument",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="argument_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Argument Session",
                "verbose_name_plural": "Argument Sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ArgumentMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("opponent", "Opponent")],
                        help_text="Who sent this message",
                        max_length=10,
                    ),
                ),
                ("content", models.TextField(help_text="Message content")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        help_text="The argument session this message belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="argument.argumentsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Argument Message",
                "verbose_name_plural": "Argument Messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArgumentAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "technical_score",
                    models.PositiveSmallIntegerField(
                        help_text="Technical accuracy score (1-10)"
                    ),
                ),
                (
                    "temperament_score",
                    models.PositiveSmallIntegerField(
                        help_text="Emotional control score (1-10)"
                    ),
                ),
                (
                    "focus_score",
                    models.PositiveSmallIntegerField(
                        help_text="Topic focus score (1-10)"
                    ),
                ),
                (
                    "technical_feedback",
                    models.TextField(
                        help_text="Feedback on technical accuracy of user's arguments"
                    ),
                ),
                (
                    "temperament_feedback",
                    models.TextField(
                        help_text="Feedback on user's temperament and professionalism"
                    ),
                ),
                (
                    "focus_feedback",
                    models.TextField(help_text="Feedback on staying on topic"),
                ),
                (
                    "overall_feedback",
                    models.TextField(
                        help_text="Overall summary and advice for improvement"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.OneToOneField(
                        help_text="The argument session this analysis belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="argument.argumentsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Argument Analysis",
                "verbose_name_plural": "Argument Analyses",
            },
        ),
        migrations.AddIndex(
            model_name="argumentsession",
            index=models.Index(
                fields=["user", "status"], name="argument_ar_user_id_5d816f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="argumentsession",
            index=models.Index(
                fields=["subject", "status"], name="argument_ar_subject_370b3a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="argumentmessage",
            index=models.Index(
                fields=["session", "created_at"], name="argument_ar_session_cceed7_idx"
            ),
        ),
    ]
