# Generated by Django 6.0.3 on 2026-03-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for the subject (e.g., 'LightGBM')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier for the subject",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Short description shown in the subject picker",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        db_index=True,
                        help_text="Grouping label (e.g., 'ML Frameworks', 'Python Core')",
                        max_length=50,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Optional icon identifier for the UI (e.g., icon class name)",
                        max_length=50,
                    ),
                ),
                (
                    "supports_visuals",
                    models.BooleanField(
                        default=False,
                        help_text="Whether Visuals mode is available for this subject",
                    ),
                ),
                (
                    "default_question_count",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Default number of questions for Exam mode",
                    ),
                ),
                (
                    "difficulty_levels",
                    models.JSONField(
                        default=list,
                        help_text="Available difficulty tiers (e.g., ['beginner', 'intermediate', 'advanced'])",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Soft-disable toggle for the subject",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
                "ordering": ["category", "name"],
            },
        ),
    ]
