# Generated by Django 6.0.3 on 2026-03-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="coding_language",
            field=models.CharField(
                blank=True,
                help_text="If this subject has its own coding language (e.g., 'git', 'sql', 'shell'), specify it here. Leave blank for Python-only subjects like LightGBM.",
                max_length=20,
            ),
        ),
    ]
