# Generated by Django 6.0.3 on 2026-03-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0002_subject_coding_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="supports_math",
            field=models.BooleanField(
                default=False,
                help_text="Whether 'Can I Math?' mode is available for this subject",
            ),
        ),
    ]
