# Generated by Django 6.0.3 on 2026-03-07 23:52

from django.db import migrations


def add_interview_to_difficulty_levels(apps, schema_editor):
    """Add 'interview' to difficulty_levels for all subjects that don't have it."""
    Subject = apps.get_model("subjects", "Subject")
    for subject in Subject.objects.all():
        if "interview" not in subject.difficulty_levels:
            subject.difficulty_levels.append("interview")
            subject.save(update_fields=["difficulty_levels"])


def remove_interview_from_difficulty_levels(apps, schema_editor):
    """Remove 'interview' from difficulty_levels (reverse migration)."""
    Subject = apps.get_model("subjects", "Subject")
    for subject in Subject.objects.all():
        if "interview" in subject.difficulty_levels:
            subject.difficulty_levels.remove("interview")
            subject.save(update_fields=["difficulty_levels"])


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0003_add_supports_math"),
    ]

    operations = [
        migrations.RunPython(
            add_interview_to_difficulty_levels,
            remove_interview_from_difficulty_levels,
        ),
    ]
