# Generated by Django 6.0.3 on 2026-03-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0004_add_interview_difficulty"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="supports_systemdesign",
            field=models.BooleanField(
                default=False,
                help_text="Whether 'Design Your System' mode is available for this subject",
            ),
        ),
    ]
