# Generated by Django 6.0.3 on 2026-03-11 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemDesignChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Challenge title, e.g., 'Design Twitter'",
                        max_length=200,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(help_text="URL-safe identifier", unique=True),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Full problem statement presented to the user"
                    ),
                ),
                (
                    "functional_requirements",
                    models.JSONField(
                        default=list,
                        help_text="List of functional requirements the design should address",
                    ),
                ),
                (
                    "non_functional_requirements",
                    models.JSONField(
                        default=list,
                        help_text="List of non-functional requirements (scalability, latency, etc.)",
                    ),
                ),
                (
                    "constraints",
                    models.JSONField(
                        default=list,
                        help_text="System constraints (budget, region, compliance)",
                    ),
                ),
                (
                    "evaluation_criteria",
                    models.JSONField(
                        default=dict,
                        help_text="Rubric criteria with weights: {scalability: 10, reliability: 10, ...}",
                    ),
                ),
                (
                    "reference_solution_description",
                    models.TextField(
                        blank=True,
                        help_text="Text description of an ideal solution approach",
                    ),
                ),
                (
                    "reference_components",
                    models.JSONField(
                        default=list,
                        help_text="Expected components: ['load_balancer', 'cache', 'database', ...]",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        db_index=True,
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                (
                    "time_limit_seconds",
                    models.PositiveIntegerField(
                        default=1800, help_text="Time limit based on difficulty"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manually Created"),
                            ("llm", "LLM Generated"),
                        ],
                        default="manual",
                        max_length=10,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text="Tags for categorization"
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System Design Challenge",
                "verbose_name_plural": "System Design Challenges",
                "ordering": ["difficulty", "title"],
            },
        ),
        migrations.CreateModel(
            name="SystemDesignSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "surprise_challenge_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="LLM-generated challenge details when using surprise mode",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                ("time_limit_seconds", models.PositiveIntegerField(default=1800)),
                (
                    "canvas_state",
                    models.JSONField(
                        default=dict,
                        help_text="Fabric.js canvas JSON state for persistence",
                    ),
                ),
                (
                    "canvas_snapshot_png",
                    models.BinaryField(
                        blank=True,
                        help_text="Latest PNG snapshot of the canvas for vision analysis",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("submitted", "Submitted for Scoring"),
                            ("completed", "Completed"),
                            ("timed_out", "Timed Out"),
                            ("abandoned", "Abandoned"),
                        ],
                        db_index=True,
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_analysis_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the last auto-analysis was performed",
                        null=True,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="systemdesign.systemdesignchallenge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="systemdesign_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Design Session",
                "verbose_name_plural": "System Design Sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemDesignScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scalability_score",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Score for scalability considerations (1-10)",
                    ),
                ),
                (
                    "reliability_score",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Score for fault tolerance and reliability (1-10)",
                    ),
                ),
                (
                    "performance_score",
                    models.PositiveIntegerField(
                        default=0, help_text="Score for performance optimization (1-10)"
                    ),
                ),
                (
                    "cost_efficiency_score",
                    models.PositiveIntegerField(
                        default=0, help_text="Score for cost-effective choices (1-10)"
                    ),
                ),
                (
                    "communication_score",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Score for communication quality in chat (1-10)",
                    ),
                ),
                (
                    "overall_score",
                    models.PositiveIntegerField(
                        default=0, help_text="Weighted overall score (1-100)"
                    ),
                ),
                (
                    "strengths_narrative",
                    models.TextField(blank=True, help_text="What the user did well"),
                ),
                (
                    "weaknesses_narrative",
                    models.TextField(blank=True, help_text="Areas for improvement"),
                ),
                (
                    "design_coherence_feedback",
                    models.TextField(
                        blank=True, help_text="How well the components work together"
                    ),
                ),
                (
                    "comparison_to_reference",
                    models.TextField(
                        blank=True,
                        help_text="Comparison to the reference/ideal solution",
                    ),
                ),
                (
                    "detailed_feedback",
                    models.JSONField(
                        default=dict,
                        help_text="Full scoring breakdown with justifications per category",
                    ),
                ),
                (
                    "scoring_model_used",
                    models.CharField(
                        blank=True,
                        help_text="Model used for scoring (e.g., claude-3-opus)",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_score",
                        to="systemdesign.systemdesignsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "System Design Score",
                "verbose_name_plural": "System Design Scores",
            },
        ),
        migrations.CreateModel(
            name="SystemDesignMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Interviewer"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("clarification", "Clarification Question"),
                            ("hint", "Hint Request"),
                            ("analysis", "Diagram Analysis"),
                            ("general", "General Discussion"),
                            ("initial", "Initial Prompt"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("token_count_estimate", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="systemdesign.systemdesignsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="DiagramAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("periodic", "Periodic Auto-Analysis"),
                            ("on_demand", "On-Demand Analysis"),
                            ("final", "Final Submission Analysis"),
                        ],
                        default="periodic",
                        max_length=20,
                    ),
                ),
                (
                    "canvas_state_snapshot",
                    models.JSONField(
                        default=dict,
                        help_text="Fabric.js JSON state at time of analysis",
                    ),
                ),
                (
                    "canvas_png_snapshot",
                    models.BinaryField(
                        blank=True,
                        help_text="PNG snapshot at time of analysis",
                        null=True,
                    ),
                ),
                (
                    "identified_components",
                    models.JSONField(
                        default=list, help_text="Components detected in the diagram"
                    ),
                ),
                (
                    "identified_connections",
                    models.JSONField(
                        default=list, help_text="Data flows/connections detected"
                    ),
                ),
                ("strengths", models.JSONField(default=list)),
                ("concerns", models.JSONField(default=list)),
                ("suggestions", models.JSONField(default=list)),
                ("overall_impression", models.TextField(blank=True)),
                (
                    "preliminary_scores",
                    models.JSONField(
                        default=dict,
                        help_text="Preliminary scores: {scalability: 6, reliability: 7, ...}",
                    ),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw response from the vision API",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="systemdesign.systemdesignsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diagram Analysis",
                "verbose_name_plural": "Diagram Analyses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="systemdesignsession",
            index=models.Index(
                fields=["user", "status"], name="systemdesig_user_id_7b9c3e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="systemdesignmessage",
            index=models.Index(
                fields=["session", "created_at"], name="systemdesig_session_e581f2_idx"
            ),
        ),
    ]
