# Generated by Django 6.0.3 on 2026-03-05 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subjects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CodingChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief title for the challenge", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Full problem description with requirements"
                    ),
                ),
                (
                    "challenge_type",
                    models.CharField(
                        choices=[
                            ("implement", "Implement from Scratch"),
                            ("modify", "Modify Existing Code"),
                        ],
                        db_index=True,
                        default="implement",
                        help_text="Type of challenge: implement or modify",
                        max_length=20,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("python", "Python"),
                            ("javascript", "JavaScript"),
                            ("sql", "SQL"),
                        ],
                        db_index=True,
                        default="python",
                        help_text="Programming language for this challenge",
                        max_length=20,
                    ),
                ),
                (
                    "starter_code",
                    models.TextField(
                        blank=True, help_text="Initial code provided to the user"
                    ),
                ),
                (
                    "reference_solution",
                    models.TextField(
                        blank=True,
                        help_text="Reference solution for evaluation context",
                    ),
                ),
                (
                    "evaluation_criteria",
                    models.JSONField(
                        default=list,
                        help_text="List of criteria Claude should evaluate against",
                    ),
                ),
                (
                    "expected_output",
                    models.TextField(
                        blank=True, help_text="Expected output or behavior description"
                    ),
                ),
                (
                    "hints",
                    models.JSONField(
                        default=list, help_text="List of hints that can be revealed"
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        db_index=True,
                        default="intermediate",
                        help_text="Difficulty level of the challenge",
                        max_length=20,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags for categorizing the challenge",
                    ),
                ),
                (
                    "estimated_time_minutes",
                    models.PositiveIntegerField(
                        default=15, help_text="Estimated time to complete in minutes"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("claude_api", "Claude API Generated"),
                            ("manual", "Manually Created"),
                        ],
                        db_index=True,
                        default="claude_api",
                        help_text="Where this challenge originated from",
                        max_length=20,
                    ),
                ),
                (
                    "source_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Hash for deduplication",
                        max_length=64,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this challenge is available for use",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="The subject area this challenge belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coding_challenges",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coding Challenge",
                "verbose_name_plural": "Coding Challenges",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CodingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "challenge_type",
                    models.CharField(
                        choices=[
                            ("implement", "Implement from Scratch"),
                            ("modify", "Modify Existing Code"),
                        ],
                        help_text="Type of challenge at time of session",
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        help_text="Difficulty level at time of session", max_length=20
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("python", "Python"),
                            ("javascript", "JavaScript"),
                            ("sql", "SQL"),
                        ],
                        help_text="Programming language",
                        max_length=20,
                    ),
                ),
                (
                    "user_code",
                    models.TextField(blank=True, help_text="The user's current code"),
                ),
                (
                    "hints_used",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of hints revealed"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("submitted", "Submitted for Evaluation"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        db_index=True,
                        default="in_progress",
                        help_text="Current status of the session",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, help_text="When the code was submitted", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When evaluation was completed", null=True
                    ),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        help_text="The challenge being attempted",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="coding.codingchallenge",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="The subject area for this session",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coding_sessions",
                        to="subjects.subject",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user attempting this challenge",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coding_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Coding Session",
                "verbose_name_plural": "Coding Sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="CodingResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submitted_code",
                    models.TextField(help_text="The code submitted for evaluation"),
                ),
                (
                    "submission_number",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Attempt number (if multiple submissions allowed)",
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        help_text="Whether the solution is functionally correct",
                        null=True,
                    ),
                ),
                (
                    "overall_score",
                    models.PositiveIntegerField(
                        help_text="Overall score out of 100", null=True
                    ),
                ),
                (
                    "evaluation_result",
                    models.JSONField(
                        default=dict, help_text="Full evaluation result from Claude"
                    ),
                ),
                (
                    "correctness_score",
                    models.PositiveIntegerField(
                        help_text="Score for functional correctness (0-100)", null=True
                    ),
                ),
                (
                    "style_score",
                    models.PositiveIntegerField(
                        help_text="Score for code style/conventions (0-100)", null=True
                    ),
                ),
                (
                    "completeness_score",
                    models.PositiveIntegerField(
                        help_text="Score for completeness of solution (0-100)",
                        null=True,
                    ),
                ),
                (
                    "efficiency_score",
                    models.PositiveIntegerField(
                        help_text="Score for algorithmic efficiency (0-100)", null=True
                    ),
                ),
                (
                    "summary_feedback",
                    models.TextField(
                        blank=True, help_text="High-level summary of the evaluation"
                    ),
                ),
                (
                    "detailed_feedback",
                    models.TextField(
                        blank=True,
                        help_text="Detailed explanation of issues and suggestions",
                    ),
                ),
                (
                    "areas_for_improvement",
                    models.JSONField(
                        default=list, help_text="List of specific areas to improve"
                    ),
                ),
                (
                    "strengths",
                    models.JSONField(
                        default=list, help_text="List of things done well"
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "evaluated_at",
                    models.DateTimeField(
                        blank=True, help_text="When evaluation was completed", null=True
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        help_text="The session this response belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="coding.codingsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coding Response",
                "verbose_name_plural": "Coding Responses",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.AddIndex(
            model_name="codingchallenge",
            index=models.Index(
                fields=["subject", "difficulty", "is_active"],
                name="coding_codi_subject_c37437_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="codingchallenge",
            index=models.Index(
                fields=["subject", "challenge_type", "is_active"],
                name="coding_codi_subject_ea9e3f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="codingchallenge",
            index=models.Index(
                fields=["subject", "language", "is_active"],
                name="coding_codi_subject_807c23_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="codingsession",
            index=models.Index(
                fields=["user", "status"], name="coding_codi_user_id_8f7fb7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codingsession",
            index=models.Index(
                fields=["subject", "status"], name="coding_codi_subject_ec3995_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codingresponse",
            index=models.Index(
                fields=["session", "submission_number"],
                name="coding_codi_session_7b0b60_idx",
            ),
        ),
    ]
