# Generated by Django 6.0.3 on 2026-03-07 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coding", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codingchallenge",
            name="language",
            field=models.CharField(
                choices=[
                    ("python", "Python"),
                    ("javascript", "JavaScript"),
                    ("sql", "SQL"),
                    ("git", "Git Commands"),
                    ("shell", "Shell/Bash"),
                    ("docker", "Docker"),
                ],
                db_index=True,
                default="python",
                help_text="Programming language for this challenge",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="codingsession",
            name="language",
            field=models.CharField(
                choices=[
                    ("python", "Python"),
                    ("javascript", "JavaScript"),
                    ("sql", "SQL"),
                    ("git", "Git Commands"),
                    ("shell", "Shell/Bash"),
                    ("docker", "Docker"),
                ],
                help_text="Programming language",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Test",
                        help_text="Descriptive name for the test case",
                        max_length=100,
                    ),
                ),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("return", "Return Value"),
                            ("stdout", "Standard Output"),
                            ("assert", "Assertion"),
                        ],
                        default="return",
                        help_text="How to validate the test: return value, stdout, or assertion",
                        max_length=10,
                    ),
                ),
                (
                    "function_name",
                    models.CharField(
                        default="solution",
                        help_text="Name of the function to call",
                        max_length=100,
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(
                        default=dict,
                        help_text="Arguments to pass to the function (as kwargs)",
                    ),
                ),
                (
                    "expected_output",
                    models.JSONField(
                        blank=True,
                        help_text="Expected return value or stdout content",
                        null=True,
                    ),
                ),
                (
                    "assertion_code",
                    models.TextField(
                        blank=True,
                        help_text="Custom assertion code for assertion-type tests",
                    ),
                ),
                (
                    "is_hidden",
                    models.BooleanField(
                        default=False,
                        help_text="Hidden tests are only shown after submission",
                    ),
                ),
                (
                    "is_sample",
                    models.BooleanField(
                        default=False,
                        help_text="Sample tests are shown in the problem description",
                    ),
                ),
                (
                    "is_llm_generated",
                    models.BooleanField(
                        default=True, help_text="Whether this test was generated by LLM"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order for test cases"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        help_text="The challenge this test case belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="coding.codingchallenge",
                    ),
                ),
            ],
            options={
                "verbose_name": "Test Case",
                "verbose_name_plural": "Test Cases",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExecutionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("error", "Runtime Error"),
                            ("timeout", "Timeout"),
                        ],
                        help_text="Whether the test passed, failed, errored, or timed out",
                        max_length=10,
                    ),
                ),
                (
                    "actual_output",
                    models.JSONField(
                        blank=True,
                        help_text="The actual return value or stdout from execution",
                        null=True,
                    ),
                ),
                (
                    "stdout",
                    models.TextField(
                        blank=True, help_text="Standard output from the execution"
                    ),
                ),
                (
                    "stderr",
                    models.TextField(
                        blank=True, help_text="Standard error from the execution"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if execution failed"
                    ),
                ),
                (
                    "execution_time_ms",
                    models.PositiveIntegerField(
                        default=0, help_text="Execution time in milliseconds"
                    ),
                ),
                (
                    "memory_used_bytes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Memory used in bytes (if available)",
                        null=True,
                    ),
                ),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "response",
                    models.ForeignKey(
                        help_text="The code submission this result belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_results",
                        to="coding.codingresponse",
                    ),
                ),
                (
                    "test_case",
                    models.ForeignKey(
                        help_text="The test case that was executed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_results",
                        to="coding.testcase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Execution Result",
                "verbose_name_plural": "Execution Results",
                "ordering": ["test_case__order", "executed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="testcase",
            index=models.Index(
                fields=["challenge", "is_hidden"], name="coding_test_challen_6aa820_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="executionresult",
            index=models.Index(
                fields=["response", "status"], name="coding_exec_respons_0d448b_idx"
            ),
        ),
    ]
